# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc ""
  homepage ""
  version "0.0.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdhayford/kit/releases/download/v0.0.6/kit_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "440c4a816e6f3d39e7ce7272c4c9dfd533d58935ae5c7891d83d2d2ddb607a02"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdhayford/kit/releases/download/v0.0.6/kit_0.0.6_Darwin_arm64.tar.gz"
      sha256 "9f2bd5a52bd25f932a846885252b9adc635b57da1ef560b417d5a8456871167e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jdhayford/kit/releases/download/v0.0.6/kit_0.0.6_Linux_x86_64.tar.gz"
      sha256 "b76971f6a573cff07d73d3fb19fcd42a756792bc85608a5784e545b2e71df5a4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdhayford/kit/releases/download/v0.0.6/kit_0.0.6_Linux_arm64.tar.gz"
      sha256 "d90519d628b3aca9d4f84918a5b8d436b79cd79f8d61022cd89eb1e9778afeaf"
    end
  end

  depends_on "git"
  depends_on "zsh" => :optional

  def install
    bin.install "kit"
  end
end
