# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc ""
  homepage ""
  version "0.0.7"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdhayford/kit/releases/download/0.0.7/kit_0.0.7_Darwin_x86_64.tar.gz"
      sha256 "8e80f011f6eb271410166240170901e1ff90854c3a8c2432c634ad0b7377f07f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdhayford/kit/releases/download/0.0.7/kit_0.0.7_Darwin_arm64.tar.gz"
      sha256 "6cd49af0690d296e6820aec64474e903908b2b7841da82bfa3f6013d43b4edfc"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jdhayford/kit/releases/download/0.0.7/kit_0.0.7_Linux_x86_64.tar.gz"
      sha256 "a61b5ec6365cecd7cee6336dde3beb67d64c51c9ef633a3281e520e1345b44e2"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdhayford/kit/releases/download/0.0.7/kit_0.0.7_Linux_arm64.tar.gz"
      sha256 "d924bf5f67aeb6df72e0b69cd3cebd27816c246bf180ddda681d2ff8a9e87a7d"
    end
  end

  depends_on "git"
  depends_on "zsh" => :optional

  def install
    bin.install "kit"
  end
end
